#! /usr/bin/python

import sqlalchemy as sa
from sqlalchemy import *
from sqlalchemy.dialects.mysql import VARCHAR
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import scoped_session
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base as dec
#from setting import Base
#from setting import ENGINE
import urllib as ul
import sys

##session

engine = sa.create_engine("mysql+pymysql://root:root@localhost/auth_info?charset=utf8", echo=False, encoding='utf8-', max_overflow=10, pool_size=6)
engine.connect()
Base = dec(bind = engine)
class Query_table(Base):

	__tablename__ = 'accepted'
	id = sa.Column('id',Integer, autoincrement = True, primary_key = True)
	account = sa.Column('account', VARCHAR(255))
	password = sa.Column('password',VARCHAR(255))
	email = sa.Column('email', VARCHAR(255))

Base.metadata.create_all(bind=engine)

session = scoped_session(sessionmaker(autocommit = False, autoflush = False, bind = engine))
if session == "":
	print("no session and try it again")
else:
	print("having session and the session is {}".format(session))

tbl = Query_table()
if tbl == False:
	print("I will create table")
	Base.metadata.create_all(bind=engine)
else:
	pass

print(session.query(tbl).all())


"""

if __name__=='__main__':
	conn = DB_state()
	conn.db_communication()
	mapper = Query_table():
	users = state(db_account).all()
	for user in users:
		print(db_account)

"""

